# Generated by Django 5.2.13 on 2026-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshistory',
            name='reasoning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
